version: '3'

services:
  app:
    image: ghcr.io/kokojacket/xinyue-search:latest
    container_name: xinyue-app
    # 如果需要本地构建
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      # 配置文件
      - /opt/docker/xinyue/app/.env:/var/www/html/.env
      # 数据目录
      - /opt/docker/xinyue/app/runtime:/var/www/html/runtime
      - /opt/docker/xinyue/app/public/uploads:/var/www/html/public/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xinyue-network
    restart: always

  mysql:
    image: mysql:5.7
    container_name: xinyue-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: www_dj_com
    volumes:
      - /opt/docker/xinyue/mysql:/var/lib/mysql
      - /opt/docker/xinyue/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - xinyue-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  xinyue-network:
    driver: bridge