name: 构建并推送Docker镜像

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:  # 允许手动触发
    inputs:
      version:
        description: '指定版本号 (例如: 1.0.0)'
        required: true
        default: ''
      update_latest:
        description: '同时更新latest标签'
        required: true
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  # 使用GitHub仓库名称作为镜像名称
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 设置权限以允许推送到GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置自定义标签
        id: custom_tags
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        run: |
          TAGS="type=raw,value=v${{ github.event.inputs.version }}"
          TAGS="${TAGS}\ntype=raw,value=${{ github.event.inputs.version }}"
          if [[ "${{ github.event.inputs.update_latest }}" == "true" ]]; then
            TAGS="${TAGS}\ntype=raw,value=latest"
          fi
          echo "custom_tags<<EOF" >> $GITHUB_OUTPUT
          echo -e "${TAGS}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 设置Docker元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # 设置标签策略
          tags: |
            ${{ steps.custom_tags.outputs.custom_tags }}
            ${{ github.event_name != 'workflow_dispatch' && 'type=ref,event=branch' || '' }}
            ${{ github.event_name != 'workflow_dispatch' && 'type=ref,event=pr' || '' }}
            ${{ github.event_name != 'workflow_dispatch' && 'type=semver,pattern={{version}}' || '' }}
            ${{ github.event_name != 'workflow_dispatch' && 'type=semver,pattern={{major}}.{{minor}}' || '' }}
            ${{ github.event_name != 'workflow_dispatch' && 'type=sha,format=short' || '' }}
            ${{ github.event_name != 'workflow_dispatch' && 'type=raw,value=latest,enable={{is_default_branch}}' || '' }}

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'linux/amd64,linux/arm64'

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到GitHub容器注册表
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 镜像摘要
        run: echo ${{ steps.build-and-push.outputs.digest }} 